name: esewa_wallet
description: A Flutter package for integrating eSewa payments using InAppWebView
version: 1.0.0
homepage: https://github.com/yourusername/esewa_wallet

environment:
  sdk: ^3.8.1
  flutter: ^3.13.0

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.1.5
  crypto:
    ^3.0.6
    # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
